# TOML configs are used since alacritty (>= 0.13)

working_directory = "None"

live_config_reload = true

[env]
#TERM = "xterm-256color"
# Alacritty snap package comes with libtinfo6.3 which is picked and rejected by tmux (it requres 6.4)
# Removing predefined LD_LIBRARY_PATH exposes system-wide library first
# Alternative solution: export LD_LIBRARY_PATH = "/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH"
LD_LIBRARY_PATH = ""

[font]
size = 10.0

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Light"

[cursor]
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true

[mouse]
hide_when_typing = true

[cursor.style]
shape = "Block"
blinking = "Always"

#[colors]
#draw_bold_text_with_bright_colors = false

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

